apiVersion: v1
kind: Secret
metadata:
  name: flask-db-secret
type: Opaque
stringData:
  DB_HOST: "mydb.cu9gmuueigg2.us-east-1.rds.amazonaws.com"  # from terraform output mydb.cu9gmuueigg2.us-east-1.rds.amazonaws.com
  DB_USER: "sakshith"
  DB_PASS: "t{uzNr9dv]{Af7p*"
  DB_NAME: "userdb"
  SECRET_KEY: "supersecretkey123"
