# k8s-secret.yaml (example - do NOT commit secrets in repo)
apiVersion: v1
kind: Secret
metadata:
  name: flask-db-secret
type: Opaque
stringData:
  DB_USER: "sakshith"
  DB_PASS: "REPLACE_WITH_REAL_PASSWORD"
  DB_HOST: "sakshith-mysql.cu9gmuueigg2.us-east-1.rds.amazonaws.com"
  DB_NAME: "userdb"
