apiVersion: v1
kind: Secret
metadata:
  name: flask-db-secret
type: Opaque
stringData:
  DB_HOST: "mydb.xxxxxxx.us-east-1.rds.amazonaws.com"  # from terraform output
  DB_USER: "sakshith"
  DB_PASS: "your-real-password-from-terraform"
  DB_NAME: "userdb"
